Repository weIT-1st/Odya-server, pull requests merged in 2023-07, with the labels that each got.

#18 ODYA-60 팔로잉/팔로워 조회 무한 스크롤 적용
  build.gradle.kts
  src/docs/asciidoc/follow.adoc
  src/main/kotlin/kr/weit/odya/config/QueryFactoryConfig.kt
  src/main/kotlin/kr/weit/odya/controller/FollowController.kt
  src/main/kotlin/kr/weit/odya/domain/follow/FollowRepository.kt
  src/main/kotlin/kr/weit/odya/service/FollowService.kt
  src/main/kotlin/kr/weit/odya/service/dto/PageResponse.kt
  src/main/kotlin/kr/weit/odya/service/dto/SliceDtos.kt
  src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/follow/FollowRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/FollowFixtures.kt
  src/test/kotlin/kr/weit/odya/support/ParamFixtures.kt
  src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
  src/test/kotlin/kr/weit/odya/support/test/BaseTests.kt
  src/test/kotlin/kr/weit/odya/support/test/RestDocsHelper.kt
Labels: development

#19 ODYA-62 프로필 조회 및 수정
  src/docs/asciidoc/follow.adoc
  src/docs/asciidoc/user.adoc
  src/main/kotlin/kr/weit/odya/config/properties/ObjectStorageProperties.kt
  src/main/kotlin/kr/weit/odya/controller/ExceptionHandler.kt
  src/main/kotlin/kr/weit/odya/controller/UserController.kt
  src/main/kotlin/kr/weit/odya/domain/profilecolor/ProfileColor.kt
  src/main/kotlin/kr/weit/odya/domain/profilecolor/ProfileColorRepository.kt
  src/main/kotlin/kr/weit/odya/domain/user/Profile.kt
  src/main/kotlin/kr/weit/odya/domain/user/User.kt
  src/main/kotlin/kr/weit/odya/domain/user/UserInformation.kt
  src/main/kotlin/kr/weit/odya/domain/user/UserRepository.kt
  src/main/kotlin/kr/weit/odya/service/AuthenticationService.kt
  src/main/kotlin/kr/weit/odya/service/FollowService.kt
  src/main/kotlin/kr/weit/odya/service/ObjectStorageService.kt
  src/main/kotlin/kr/weit/odya/service/OdyaException.kt
  src/main/kotlin/kr/weit/odya/service/ProfileColorService.kt
  src/main/kotlin/kr/weit/odya/service/UserService.kt
  src/main/kotlin/kr/weit/odya/service/dto/FollowDtos.kt
  src/main/kotlin/kr/weit/odya/service/dto/UsersDtos.kt
  src/main/kotlin/kr/weit/odya/service/generator/FileNameGenerator.kt
  src/main/kotlin/kr/weit/odya/service/generator/ProfileColorRandomIndexGenerator.kt
  src/main/kotlin/kr/weit/odya/util/ResultUtils.kt
  src/main/resources/application-database.yml
  src/main/resources/db/migration/V8__add_profile_and_profile_color.sql
  src/test/kotlin/kr/weit/odya/OdyaApplicationTests.kt
  src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/profilecolor/ProfileColorRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/user/UserRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/AuthenticationServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/ProfileColorServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/AuthFixtures.kt
  src/test/kotlin/kr/weit/odya/support/ErrorMessageFixtures.kt
  src/test/kotlin/kr/weit/odya/support/FollowFixtures.kt
  src/test/kotlin/kr/weit/odya/support/ProfileColorFixtures.kt
  src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
  src/test/kotlin/kr/weit/odya/support/config/TestMockBeanConfig.kt
  src/test/kotlin/kr/weit/odya/support/test/BaseTests.kt
  src/test/kotlin/kr/weit/odya/support/test/RestDocsHelper.kt
  src/test/resources/sql/data-h2.sql
  src/test/resources/sql/schema-h2.sql
Labels: development

#17 ODYA-48 한줄 리뷰 무한 스크롤 처리
  src/docs/asciidoc/placeReview.adoc
  src/main/kotlin/kr/weit/odya/controller/PlaceReviewController.kt
  src/main/kotlin/kr/weit/odya/controller/UserController.kt
  src/main/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepository.kt
  src/main/kotlin/kr/weit/odya/service/PlaceReviewService.kt
  src/main/kotlin/kr/weit/odya/service/dto/PlaceReviewDtos.kt
  src/main/kotlin/kr/weit/odya/service/dto/SliceDtos.kt
  src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/ParamFixtures.kt
  src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
  src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
Labels: development

#22 ODYA-75 회원가입 로직 수정
  src/main/kotlin/kr/weit/odya/controller/AuthController.kt
  src/main/kotlin/kr/weit/odya/service/AuthenticationService.kt
  src/test/kotlin/kr/weit/odya/controller/AuthControllerTest.kt
  src/test/kotlin/kr/weit/odya/service/AuthenticationServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt
Labels: bug

#23 ODYA-82 서버 이슈트랜지션 적용
  .github/workflows/issueTransition.yml
Labels: ci/cd

#25 ODYA-66 API 에러 응답에 에러 코드 추가
  src/docs/asciidoc/auth.adoc
  src/docs/asciidoc/follow.adoc
  src/docs/asciidoc/overview.adoc
  src/docs/asciidoc/test.adoc
  src/docs/asciidoc/user.adoc
  src/main/kotlin/kr/weit/odya/client/ClientException.kt
  src/main/kotlin/kr/weit/odya/config/handler/CustomAuthenticationEntryPoint.kt
  src/main/kotlin/kr/weit/odya/controller/AuthController.kt
  src/main/kotlin/kr/weit/odya/controller/ExceptionHandler.kt
  src/main/kotlin/kr/weit/odya/security/FirebaseTokenHelper.kt
  src/main/kotlin/kr/weit/odya/security/InvalidTokenException.kt
  src/main/kotlin/kr/weit/odya/security/filter/FirebaseTokenFilter.kt
  src/main/kotlin/kr/weit/odya/service/AuthenticationService.kt
  src/main/kotlin/kr/weit/odya/service/OdyaException.kt
  src/main/kotlin/kr/weit/odya/service/dto/AuthDtos.kt
  src/main/kotlin/kr/weit/odya/service/dto/ErrorResponse.kt
  src/main/kotlin/kr/weit/odya/support/exception/ErrorCode.kt
  src/main/kotlin/kr/weit/odya/support/log/Logger.kt
  src/main/kotlin/kr/weit/odya/util/ResultUtils.kt
  src/test/kotlin/kr/weit/odya/controller/AuthControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/test/TestControllerTest.kt
  src/test/kotlin/kr/weit/odya/service/AuthenticationServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/AuthFixtures.kt
  src/test/kotlin/kr/weit/odya/support/filter/TestTokenFilter.kt
Labels: development

#21 ODYA-46 장소 검색 기록 API
  build.gradle.kts
  src/docs/asciidoc/placeSearchHistory.adoc
  src/main/kotlin/kr/weit/odya/controller/PlaceSearchHistoryController.kt
  src/main/kotlin/kr/weit/odya/domain/placeSearchHistory/PlaceSearchHistory.kt
  src/main/kotlin/kr/weit/odya/domain/placeSearchHistory/PlaceSearchHistoryRepository.kt
  src/main/kotlin/kr/weit/odya/domain/user/User.kt
  src/main/kotlin/kr/weit/odya/service/PlaceSearchHistoryService.kt
  src/main/kotlin/kr/weit/odya/service/dto/PlaceSearchHistoryDto.kt
  src/main/resources/application-open-search.yml
  src/main/resources/application.yml
  src/test/kotlin/kr/weit/odya/controller/PlaceSearchHistoryControllerTest.kt
  src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/PlaceSearchHistoryServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/PlaceSearchHistoryFixtures.kt
  src/test/kotlin/kr/weit/odya/support/config/TestMockBeanConfig.kt
Labels: development

#26 ODYA-78 관심 장소 API
  src/docs/asciidoc/favoritePlace.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/placeReview.adoc
  src/docs/asciidoc/placeSearchHistory.adoc
  src/main/kotlin/kr/weit/odya/controller/FavoritePlaceController.kt
  src/main/kotlin/kr/weit/odya/domain/favoritePlace/FavoritePlace.kt
  src/main/kotlin/kr/weit/odya/domain/favoritePlace/FavoritePlaceRepository.kt
  src/main/kotlin/kr/weit/odya/service/FavoritePlaceService.kt
  src/main/kotlin/kr/weit/odya/service/dto/FavoritePlaceDtos.kt
  src/main/resources/db/migration/V9__add_favorite_place.sql
  src/test/kotlin/kr/weit/odya/controller/FavoritePlaceControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/PlaceSearchHistoryControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/favoritePlace/FavoritePlaceRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/FavoritePlaceServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/ErrorMessageFixtures.kt
  src/test/kotlin/kr/weit/odya/support/FavoritePlaceFixtures.kt
  src/test/resources/sql/schema-h2.sql
Labels: development

#27 ODYA-88 관심 장소 API(관심 장소 리스트)
  src/docs/asciidoc/favoritePlace.adoc
  src/main/kotlin/kr/weit/odya/controller/FavoritePlaceController.kt
  src/main/kotlin/kr/weit/odya/domain/favoritePlace/FavoritePlaceRepository.kt
  src/main/kotlin/kr/weit/odya/service/FavoritePlaceService.kt
  src/main/kotlin/kr/weit/odya/service/dto/FavoritePlaceDtos.kt
  src/test/kotlin/kr/weit/odya/controller/FavoritePlaceControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/favoritePlace/FavoritePlaceRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/FavoritePlaceServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/FavoritePlaceFixtures.kt
Labels: development
