Repository weIT-1st/Odya-server, pull requests merged in 2023-09, with the labels that each got.

#37 ODYA-123 레거시 걷어내기
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/test.adoc
  src/main/kotlin/kr/weit/odya/controller/TestController.kt
  src/main/kotlin/kr/weit/odya/security/filter/FirebaseTokenFilter.kt
  src/main/resources/application.yml
  src/test/kotlin/kr/weit/odya/controller/test/TestControllerTest.kt
Labels: Legacy

#41 ODYA-136 깨지는 테스트 수정
  src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepositoryTest.kt
Labels: bug

#42 ODYA-137 한줄리뷰 시간 정보 추가
  src/main/kotlin/kr/weit/odya/service/dto/PlaceReviewDtos.kt
  src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
  src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
Labels: bug

#43 ODYA-117 신고 API
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/report.adoc
  src/main/kotlin/kr/weit/odya/controller/ReportController.kt
  src/main/kotlin/kr/weit/odya/domain/agreedTerms/AgreedTermsRepository.kt
  src/main/kotlin/kr/weit/odya/domain/contentimage/ContentImageRepository.kt
  src/main/kotlin/kr/weit/odya/domain/favoriteTopic/FavoriteTopicRepository.kt
  src/main/kotlin/kr/weit/odya/domain/report/CommonReport.kt
  src/main/kotlin/kr/weit/odya/domain/report/ReportPlaceReview.kt
  src/main/kotlin/kr/weit/odya/domain/report/ReportPlaceReviewRepository.kt
  src/main/kotlin/kr/weit/odya/domain/report/ReportReason.kt
  src/main/kotlin/kr/weit/odya/domain/report/ReportTravelJournal.kt
  src/main/kotlin/kr/weit/odya/domain/report/ReportTravelJournalRepository.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelCompanionRepository.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepository.kt
  src/main/kotlin/kr/weit/odya/service/PlaceReviewService.kt
  src/main/kotlin/kr/weit/odya/service/ReportService.kt
  src/main/kotlin/kr/weit/odya/service/TravelJournalService.kt
  src/main/kotlin/kr/weit/odya/service/UserService.kt
  src/main/kotlin/kr/weit/odya/service/WithdrawService.kt
  src/main/kotlin/kr/weit/odya/service/dto/ReportDtos.kt
  src/main/resources/db/migration/V18__add_report.sql
  src/main/resources/db/migration/V21__add_place_review_and_report_index.sql
  src/test/kotlin/kr/weit/odya/controller/PlaceReviewControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/ReportControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/agreedTerms/AgreedTermsRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/contentImage/ContentImageRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/favoriteTopic/FavoriteTopicRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/follow/FollowRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/placeReview/PlaceReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/report/ReportPlaceReviewRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/report/ReportTravelJournalRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelCompanionRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/PlaceReviewServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/ReportServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/TravelJournalServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/WithdrawServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/ErrorMessageFixtures.kt
  src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
  src/test/kotlin/kr/weit/odya/support/ReportFixtures.kt
  src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
  src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
  src/test/resources/sql/schema-h2.sql
Labels: development

#52 ODYA-144 여행 일지 추가 기능 구현
  src/docs/asciidoc/travelJournal.adoc
  src/main/kotlin/kr/weit/odya/controller/TravelJournalController.kt
  src/main/kotlin/kr/weit/odya/domain/community/CommunityRepository.kt
  src/main/kotlin/kr/weit/odya/domain/follow/FollowRepository.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/Coordinates.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelCompanion.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelCompanionRepository.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournal.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalContent.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalContentImage.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalContentInformation.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalContentUpdateEvent.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalDeleteEvent.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalInformation.kt
  src/main/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepository.kt
  src/main/kotlin/kr/weit/odya/listener/TravelJournalEventListener.kt
  src/main/kotlin/kr/weit/odya/service/TravelJournalService.kt
  src/main/kotlin/kr/weit/odya/service/dto/TravelJournalDtos.kt
  src/main/resources/db/migration/V25__add_travel_journal_index.sql
  src/test/kotlin/kr/weit/odya/controller/ImageControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/TravelJournalControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/community/CommunityRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/traveljournal/TravelJournalRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/TravelJournalServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
  src/test/kotlin/kr/weit/odya/support/test/TestEntityManager.kt
Labels: development

#55 ODYA-145 커뮤니티 추가 기능 구현
  src/docs/asciidoc/community.adoc
  src/main/kotlin/kr/weit/odya/controller/CommunityController.kt
  src/main/kotlin/kr/weit/odya/controller/ExceptionHandler.kt
  src/main/kotlin/kr/weit/odya/domain/community/Community.kt
  src/main/kotlin/kr/weit/odya/domain/community/CommunityContentImage.kt
  src/main/kotlin/kr/weit/odya/domain/community/CommunityEvents.kt
  src/main/kotlin/kr/weit/odya/domain/community/CommunityInformation.kt
  src/main/kotlin/kr/weit/odya/domain/community/CommunityRepository.kt
  src/main/kotlin/kr/weit/odya/domain/communitycomment/CommunityCommentRepository.kt
  src/main/kotlin/kr/weit/odya/domain/follow/FollowRepository.kt
  src/main/kotlin/kr/weit/odya/domain/topic/TopicRepository.kt
  src/main/kotlin/kr/weit/odya/listener/CommunityEventListener.kt
  src/main/kotlin/kr/weit/odya/service/CommunityService.kt
  src/main/kotlin/kr/weit/odya/service/FileService.kt
  src/main/kotlin/kr/weit/odya/service/dto/CommunityDtos.kt
  src/main/kotlin/kr/weit/odya/service/dto/TravelJournalDtos.kt
  src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/community/CommunityRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/communitycomment/CommunityCommentRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/CommunityCommentFixtures.kt
  src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt
  src/test/kotlin/kr/weit/odya/support/MockFileFixtures.kt
  src/test/kotlin/kr/weit/odya/support/PlaceReviewFixture.kt
  src/test/kotlin/kr/weit/odya/support/TopicFixtures.kt
  src/test/kotlin/kr/weit/odya/support/TravelJournalFixtures.kt
Labels: development

#56 ODYA-155 전화번호로 유저 검색
  src/docs/asciidoc/user.adoc
  src/main/kotlin/kr/weit/odya/controller/UserController.kt
  src/main/kotlin/kr/weit/odya/domain/user/UserRepository.kt
  src/main/kotlin/kr/weit/odya/service/UserService.kt
  src/main/kotlin/kr/weit/odya/service/dto/UsersDtos.kt
  src/test/kotlin/kr/weit/odya/controller/UserControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/user/UserRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/ParamFixtures.kt
  src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
Labels: development

#57 ODYA-154 팔로워 검색
  src/docs/asciidoc/follow.adoc
  src/main/kotlin/kr/weit/odya/controller/FollowController.kt
  src/main/kotlin/kr/weit/odya/domain/follow/FollowRepository.kt
  src/main/kotlin/kr/weit/odya/service/FollowService.kt
  src/test/kotlin/kr/weit/odya/controller/FollowControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/follow/FollowRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/FollowServiceTest.kt
Labels: development

#59 ODYA-143 커뮤니티 좋아요 기능
  build.gradle.kts
  src/docs/asciidoc/communityLike.adoc
  src/docs/asciidoc/index.adoc
  src/docs/asciidoc/overview.adoc
  src/main/kotlin/kr/weit/odya/controller/CommunityLikeController.kt
  src/main/kotlin/kr/weit/odya/domain/community/Community.kt
  src/main/kotlin/kr/weit/odya/domain/community/CommunityRepository.kt
  src/main/kotlin/kr/weit/odya/domain/communitycomment/CommunityCommentRepository.kt
  src/main/kotlin/kr/weit/odya/domain/communitylike/CommunityLike.kt
  src/main/kotlin/kr/weit/odya/domain/communitylike/CommunityLikeId.kt
  src/main/kotlin/kr/weit/odya/domain/communitylike/CommunityLikeRepository.kt
  src/main/kotlin/kr/weit/odya/domain/report/ReportCommunityRepository.kt
  src/main/kotlin/kr/weit/odya/domain/report/ReportTravelJournalRepository.kt
  src/main/kotlin/kr/weit/odya/service/CommunityLikeFacade.kt
  src/main/kotlin/kr/weit/odya/service/CommunityLikeService.kt
  src/main/kotlin/kr/weit/odya/service/CommunityService.kt
  src/main/kotlin/kr/weit/odya/service/OdyaException.kt
  src/main/kotlin/kr/weit/odya/service/UserService.kt
  src/main/kotlin/kr/weit/odya/service/dto/CommunityDtos.kt
  src/main/kotlin/kr/weit/odya/support/exception/ErrorCode.kt
  src/main/resources/db/migration/V27__add_community_like.sql
  src/main/resources/db/migration/V29__alter_community.sql
  src/test/kotlin/kr/weit/odya/controller/CommunityControllerTest.kt
  src/test/kotlin/kr/weit/odya/controller/CommunityLikeControllerTest.kt
  src/test/kotlin/kr/weit/odya/domain/community/CommunityRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/communitycomment/CommunityCommentRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/communitylike/CommunityLikeRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/domain/report/ReportCommunityRepositoryTest.kt
  src/test/kotlin/kr/weit/odya/service/CommunityLikeFacadeTest.kt
  src/test/kotlin/kr/weit/odya/service/CommunityLikeServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/CommunityServiceTest.kt
  src/test/kotlin/kr/weit/odya/service/UserServiceTest.kt
  src/test/kotlin/kr/weit/odya/support/CommunityFixtures.kt
  src/test/kotlin/kr/weit/odya/support/CommunityLikeFixtures.kt
  src/test/kotlin/kr/weit/odya/support/UserFixtures.kt
  src/test/kotlin/kr/weit/odya/support/config/TestMockBeanConfig.kt
  src/test/resources/sql/schema-h2.sql
Labels: development
